### ISSUE TITLE
game crash 1.18.1

### ISSUE THREAD

**Issue by Numbers949** [oitsjustjose/Natural-Progression#58]
after the first chop level the came crashes. 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/20/22, 12:16 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at ht.treechop.common.block.ChoppedLogBlock$Entity.m_183515_(ChoppedLogBlock.java:291) ~[TreeChop-1.18.1-0.15.4.jar%2390!/:0.15.4] {re:classloading}
	at net.minecraft.world.level.block.entity.BlockEntity.m_187482_(BlockEntity.java:75) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:InstanceRemoveMixin,pl:mixin:A}
	at ht.treechop.common.block.ChoppedLogBlock$Entity.m_5995_(ChoppedLogBlock.java:326) ~[TreeChop-1.18.1-0.15.4.jar%2390!/:0.15.4] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,re:classloading}
	at ht.treechop.common.block.ChoppedLogBlock$Entity.getUpdatePacket(ChoppedLogBlock.java:332) ~[TreeChop-1.18.1-0.15.4.jar%2390!/:0.15.4] {re:classloading}
	at ht.treechop.common.block.ChoppedLogBlock$Entity.m_183216_(ChoppedLogBlock.java:261) ~[TreeChop-1.18.1-0.15.4.jar%2390!/:0.15.4] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:553) ~[forge-1.18.1-39.0.45-universal.jar%2395!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:227) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,re:classloading,pl:mixin:APP:pehkui.mixins.json:ServerPlayerInteractionManagerMixin,pl:mixin:APP:pehkui.mixins.json:reach.ServerPlayerInteractionManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,re:classloading,pl:mixin:APP:pehkui.mixins.json:ServerPlayerInteractionManagerMixin,pl:mixin:APP:pehkui.mixins.json:reach.ServerPlayerInteractionManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,re:classloading,pl:mixin:APP:pehkui.mixins.json:ServerPlayerInteractionManagerMixin,pl:mixin:APP:pehkui.mixins.json:reach.ServerPlayerInteractionManagerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$checkThreadAndEnqueue$0(PacketUtils.java:38) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[OptiFine_1.18.1_HD_U_H4.jar%2396!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:193) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:158) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:135) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by oitsjustjose** [comment]
This mod isn't made by me, this is a bug with [HT's Tree Chop](https://github.com/hammertater/treechop/issues). Please post this there.
