### ISSUE TITLE
Incompatibility with 1.20.1 Jade

### ISSUE THREAD

**Issue by D0CTOR-ZED** [oitsjustjose/Natural-Progression#84]
Minecraft version 1.20.1
Forge 47.2.19

When running just Forge, Natural Progression, and Jade for minecraft 1.20.1, looking at a stone block acts as if the player is trying to break the stone block with an unapproved tool. Jade calls getDestroyProgress when determining how to render block breaking progress, which I believe is the trigger for the issue.

As the stone breaking code is similar with the one for wood (was there a third material type?), that is probably affected as well.

I generated a stack trace during the break speed to determine why the event was being triggered.  
```
    at TRANSFORMER/forge@47.2.14/net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:189)
    at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.getDigSpeed(Player.java:721)
    at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour.m_5880_(BlockBehaviour.java:370)
    at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60625_(BlockBehaviour.java:641)
    at TRANSFORMER/jade@11.7.1/snownee.jade.JadeClient.drawBreakingProgress(JadeClient.java:237)
    at TRANSFORMER/jade@11.7.1/snownee.jade.overlay.OverlayRenderer.lambda$renderOverlay$0(OverlayRenderer.java:209)
    at TRANSFORMER/jade@11.7.1/snownee.jade.impl.CallbackContainer.call(CallbackContainer.java:28)
    at TRANSFORMER/jade@11.7.1/snownee.jade.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:208)
    at TRANSFORMER/jade@11.7.1/snownee.jade.overlay.OverlayRenderer.renderOverlay478757(OverlayRenderer.java:149)
    at TRANSFORMER/jade@11.7.1/snownee.jade.util.ClientProxy.onRenderTick(ClientProxy.java:163)
```
Would it be possible for Natural Progression to only trigger when breaking progress is greater than 0?

**Comment by oitsjustjose** [comment]
This has been fixed via 9ac5be38313ef860720046e0cfc0e0c776a40f0a :)
